apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
spec:
  ingressClassName: nginx
  rulles:
  - host: demo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-custom-svc
            port:
              number: 8080
      - path: /legacy
        pathType: Prefix
        backend:
          service:
            name: nginx-custom-svc
            port:
              number: 8080